### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by marcuskm** [shieguy/first#2]
How do you call/open the file you dropped a link for? Should i just call the folder words.txt?

**Comment by shieguy** [comment]
Yep, exactly. Download the file to desktop (or wherever youre running treasurehunt.py on) and then call it words.txt. 

Now, the file I put in particular is 32 files. So you can either combine them into one massive file, or you can open 32 diff files and run a For loop on all of them. 

if you use this file, https://github.com/dwyl/english-words
it will work for the first two answers, but it doesnt contain blackhole which is why i presented the link with the 32 files.
